name: shopping
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.0
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  flutter_screenutil: ^1.1.0
  flushbar: ^1.10.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 700

